version: '3.4'
services:
  traefik:
    image: 'traefik:1.7-alpine'
    depends_on:
      - consul
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--entrypoints=Name:http Address::80 Compress:true"
      - "--entrypoints=Name:https Address::443 TLS Compress:true"
      - "--entrypoints=Name:traefik Address::8080"
      - --acme
      - --acme.acmelogging
      - --acme.onhostrule
      - "--acme.entrypoint=https"
      - "--acme.email=${TRAEFIK_ACME_EMAIL}"
      - --acme.tlschallenge
      - "--acme.storage=traefik/acme/account"
      - --api
      - --api.dashboard
      - "--api.entrypoint=traefik"
      - --rest
      - "--rest.entrypoint=traefik"
      - --insecureskipverify
      - "--loglevel=${TRAEFIK_LOGLEVEL}"
      - --consul
      - "--consul.endpoint=127.0.0.1:8500"
      - "--consul.prefix=traefik"

  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8300:8300"
    command:
      - agent
      - -server
      - -ui
      - "-dns-port=-1"
      - "-bind=${CONSUL_BIND}"
      - "-client=${CONSUL_BIND}"
      - "-bootstrap-expect=${CONSUL_BOOTSTRAP}"

  mesh-service:
    build: ./meshserver
    network_mode: host
    depends_on:
      - traefik
    command: --delay 10
    volumes:
      - "./config:/config"
