version: '3'
services:
  mariadb:
    restart: unless-stopped
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=tmm
      - MYSQL_PASSWORD=tmm
      - MYSQL_DATABASE=tmm
    volumes:
      - "./data/mariadb:/var/lib/mysql"

  meshserver:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - traefik
    ports:
      - 5000:5000
    env_file:
      - .env
      - default.env
    environment:
      - DB_URI="mysql+pymysql://tmm:tmm@mariadb/tmm"
      - TRAEFIK_URL="http://traefik:8080"
      - PANEL_USER=${PANEL_USER}
      - PANEL_PASS=${PANEL_PASS}
      - REFRESH_RATE=${REFRESH_RATE}

  consul:
    image: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    volumes:
      - "./data/consul:/consul/data"
    env_file:
      - .env
      - default.env
    command: agent -client=0.0.0.0 -bind=0.0.0.0 ${CONSUL_OPTS}

  traefik:
    image: 'traefik:1.7-alpine'
    env_file:
      - .env
      - default.env
    environment:
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_API_URL=${PDNS_API_URL}
    depends_on:
      - consul
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--entrypoints=Name:http Address::80 Compress:true"
      - "--entrypoints=Name:https Address::443 TLS Compress:true"
      - "--entrypoints=Name:traefik Address::8080"
      - "--acme"
      - "--acme.acmelogging"
      - "--acme.onhostrule"
      - "--acme.entrypoint=https"
      - "--acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--acme.dnschallenge"
      - "--acme.dnschallenge.provider=${TRAEFIK_DNS}"
      - "--acme.storage=traefik/acme/account"
      - "--acme.dnschallenge.delaybeforecheck=180"
      - "--api"
      - "--api.dashboard"
      - "--api.entrypoint=traefik"
      - "--rest"
      - "--rest.entrypoint=traefik"
      - "--insecureskipverify"
      - "--loglevel=${TRAEFIK_LOGLEVEL}"
      - "--consul"
      - "--consul.endpoint=${TRAEFIK_CONSUL}"
      - "--consul.prefix=traefik"
      - "${TRAEFIK_OPTS}"
