version: '3'
services:
  mariadb:
    restart: unless-stopped
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=tmm
      - MYSQL_PASSWORD=tmm
      - MYSQL_DATABASE=tmm
    volumes:
      - "./data/mariadb:/var/lib/mysql"

  meshserver:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - 5000:5000
    environment:
      - DB_URI="mysql+pymysql://tmm:tmm@mariadb/tmm"
      - PANEL_USER=admin
      - PANEL_PASS=admin

  consul:
    image: consul
    restart: unless-stopped
    network_mode: host
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - "./data/consul:/consul/data"
    command: agent -dev