version: '3.4'
services:

  traefik:
    image: 'traefik:alpine'
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    network_mode: host
    command:
      - "--entrypoints=Name:http Address::80 Compress:true"
      - "--entrypoints=Name:https Address::443 TLS Compress:true"
      - "--entrypoints=Name:traefik Address::8080"
      - --acme
      - --acme.acmelogging
      - --acme.onhostrule
      - --acme.entrypoint=https
      - "--acme.email=${ACME_EMAIL}"
      - --acme.httpchallenge
      - "--acme.httpchallenge,entrypoint=http"
      - --acme.storage=/data/acme.json
      - --api
      - --api.dashboard
      - --api.entrypoint=traefik
      - --rest
      - --rest.entrypoint=traefik
      - --insecureskipverify
      - "--loglevel=${TRAEFIK_LOGLEVEL}"
    volumes:
      - "./data:/data"

  mesh-service:
    build: .
    depends_on:
      - traefik
    env_file:
      - .env
    volumes:
      - "./config.d:/usr/src/app/config.d"
    network_mode: host
