version: '3.4'
services:
  traefik:
    image: 'traefik:1.7-alpine'
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--entrypoints=Name:http Address::80 Compress:true"
      - "--entrypoints=Name:https Address::443 TLS Compress:true"
      - "--entrypoints=Name:traefik Address::8080"
      - --acme
      - --acme.acmelogging
      - --acme.onhostrule
      - "--acme.entrypoint=https"
      - "--acme.email=${TRAEFIK_ACME_EMAIL}"
      - --acme.tlschallenge
      - "--acme.storage=traefik/acme/account"
      - --api
      - --api.dashboard
      - "--api.entrypoint=traefik"
      - --rest
      - "--rest.entrypoint=traefik"
      - --insecureskipverify
      - "--loglevel=${TRAEFIK_LOGLEVEL}"
      - "${TRAEFIK_OPTS}"

  mesh-service:
    build: ./meshserver
    network_mode: host
    depends_on:
      - traefik
    command: --delay 10
    volumes:
      - "./config:/config"
